<?php
/**
 * OpenWHM Configuration File
 * Generated by installer or created manually
 */

// Prevent direct access
if (!defined('OWHMCS') && basename($_SERVER['PHP_SELF']) === 'config.php') {
    die('Access denied');
}

define('OWHMCS', true);

// =====================================================
// DATABASE CONFIGURATION
// =====================================================
define('DB_HOST', 'localhost');
define('DB_NAME', 'openwhmcs');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_PREFIX', 'owh_');

// =====================================================
// SITE CONFIGURATION
// =====================================================
define('COMPANY_NAME', 'Your Company Name');
define('BASE_URL', 'http://localhost/openwhmcs');
define('ADMIN_URL', BASE_URL . '/admin');
define('CLIENT_URL', BASE_URL . '/client');
define('ROOT_PATH', __DIR__ . '/..');

// =====================================================
// SECURITY KEYS
// =====================================================
// IMPORTANT: Generate unique keys for production!
// Use the installer or run: php -r "echo bin2hex(random_bytes(32));"
define('ENCRYPTION_KEY', 'CHANGE_THIS_TO_A_RANDOM_32_CHARACTER_STRING');
define('CRON_KEY', 'CHANGE_THIS_TO_RANDOM_STRING');

// =====================================================
// EMAIL CONFIGURATION
// =====================================================
// Set to false to disable ALL outgoing emails
define('MAIL_ENABLED', true);

// Admin email for notifications
define('ADMIN_EMAIL', 'admin@yourdomain.com');

// =====================================================
// SYSTEM SETTINGS
// =====================================================
// Timezone - see https://www.php.net/manual/en/timezones.php
define('TIMEZONE', 'America/New_York');

// Debug mode - set to false in production!
define('DEBUG_MODE', true);

// Session lifetime in seconds (default: 2 hours)
define('SESSION_LIFETIME', 7200);

// =====================================================
// CURRENCY SETTINGS
// =====================================================
define('DEFAULT_CURRENCY', 'USD');
define('CURRENCY_SYMBOL', '$');

// =====================================================
// ADDITIONAL PATHS
// =====================================================
define('UPLOAD_PATH', ROOT_PATH . '/uploads');
define('LOG_PATH', ROOT_PATH . '/logs');
define('CACHE_PATH', ROOT_PATH . '/cache');

// =====================================================
// ERROR HANDLING
// =====================================================
if (DEBUG_MODE) {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
}

// Set timezone
date_default_timezone_set(TIMEZONE);

// Start session if not already started
if (session_status() === PHP_SESSION_NONE) {
    ini_set('session.gc_maxlifetime', SESSION_LIFETIME);
    session_set_cookie_params(SESSION_LIFETIME);
    session_start();
}
